headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/luispatino/Desktop/pati/guide/web/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/luispatino/Desktop/pati/guide/web"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://*.supabase.co https://*.maptiler.com blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://*.maptiler.com; media-src 'self' https://*.supabase.co blob:; worker-src 'self' blob:; frame-src 'none'; object-src 'none'"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]